version: "3.2"
services:
  nursery:
    image: fernapi/nursery:0.0.57-2-gcb15c1e
    ports:
      - 8080:8080
    environment:
      MAINTENANCE_JDBC_URL: jdbc:postgresql://postgres:5432/postgres?user=postgres&password=venus
      JDBC_URL: jdbc:postgresql://postgres:5432/nursery?user=postgres&password=venus
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: venus
